# 文件名改为application-dev.yml,与application.yml中spring.profiles.active中的值一致
# 项目端口号
server:
  port: 8800

# mybatis log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 数据库配置用的mysql5.7
spring:
  datasource:
    url: jdbc:mysql://<你的数据库ip和端口号>?useSSL=false
    username: <用户名>
    password: <密码>
    driver-class-name: com.mysql.jdbc.Driver